### ISSUE TITLE
Error HRESULT E_FAIL returned trying to play from FFmpegInteropMSS.CreateFromUriAsync(path);

### ISSUE THREAD

**Issue by villagra** [ffmpeginteropx/FFmpegInteropX#179]
Hi,
I was doing some tests with Jellyfin (https://jellyfin.org/) and I was trying to play this stream from their public demo:

**http://demo.jellyfin.org/stable**

http://demo.jellyfin.org/stable/Videos/1056b7d34f0fa0b8ce635428e8b27f37/stream.mov?Static=true&mediaSourceId=1056b7d34f0fa0b8ce635428e8b27f37&deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzgxLjAuNDA0NC42OSBTYWZhcmkvNTM3LjM2IEVkZy84MS4wLjQxNi4zNHwxNTg0OTAxNjM0MDYx&api_key=ddd0e62743394e5f84535fdb1e8b011c&Tag=a7d0c031b160fa9a61b7992812ded9f0

But I'm getting the exception:

{"Error HRESULT E_FAIL has been returned from a call to a COM component."}

while trying to create the FFmpegInteropMSS

FFmpegInteropMSS r = await FFmpegInteropMSS.CreateFromUriAsync(path);

It works correctly with my local jellyfin instance, but somehow it's having problems with that url.

The stream is public, the file can be downloaded and I can play it correctly in their web and via VLC with the same url.

Any ideas?

Thank you.

**Comment by mcosmin222** [comment]
Do you have the internet permission in appxmanifest?

**Comment by villagra** [comment]
Yep.
I tried with my app and with the sample app in the repo.

**Comment by lukasf** [comment]
I could reproduce the bug. This is what I found in debug out:

`https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.`

Secure transport is an apple library. Openssl unfortunately has a weird license which makes it hard to integrate with normal applications, unless you want to put openssl advertisement in each an every description of your app. So I do not include it in our ffmpeg build. Openssl V3 will get a new license, but I don't believe it will be ready before end of this year. Gnutls is LGPL, so it would theoretically work. But it has lots of dependencies itself. I gave it a short try, but I gave up after I saw how complicated it is to build. I did not really have a use case where I needed https, and noone asked, so I did not want to spend too much time with it. I might give it another try sometime, but it might take a while (and no promises).

**Comment by villagra** [comment]
Thanks for the info @lukasf! At least know we know what the problem is

**Comment by mcosmin222** [comment]
I think the standard Mediaplayer object should be able to play that stream.

**Comment by villagra** [comment]
I've been trying to add openssl to make a few tests but I can't compile ffmpeg with --enable-openssl....
I'm not a c++ dev so I'm probably screwing up in a lot of places.... here is what I've done:

1. Build openssl using vcpkg (as it was the easiest way: .\vcpkg.exe install openssl-uwp --triplet x86-uwp)
2. Modify the ps1 script to copy the openssl lib & headers into (Libs\Build\x86\include & Libs\Build\x86\lib)
3. Modify FFmpegConfig.sh and include --enable-nonfree --enable-openssl
4. Installed openssl-dev into msys2: 
`pacman -S openssl-devel`

But doesn't work... I get this error in the ffmpeg output log file:
`END ./ffconf.8R5vQss6/test.c
cl.exe -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -nologo -MD -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D_WIN32_WINNT=0x0A00 -DLZMA_API_STATIC -c -Fo./ffconf.8R5vQss6/test.o ./ffconf.8R5vQss6/test.c
test.c
./ffconf.8R5vQss6/test.c(3): error C2065: 'SSL_library_init': undeclared identifier
ERROR: openssl not found`

Any ideas? 
Thanks

**Comment by lukasf** [comment]
Hi @villagra, cool, would be great if you can get this to compile. The ffmpeg config seems to assume that the headers are in a subfoler "openssl", not directly in the include folder. So make sure you create that folder and put the includes in there.

If it still does not compile, then it might be that you need to add some defines to get things running. I'd recommend to open the openssl/ssl.h file, search for SSL_library_init and check if there are some precompiler checks around that, or check for precompiler checks in the beginning of the file. For example to compile LZMA, I had to add "-DLZMA_API_STATIC" to the ffmpeg build parameters in our FFmpegConfig.sh. Otherwise LZMA would expect dll export methods and would not find the static link (lib) methods.

**Comment by lukasf** [comment]
Closing this as duplicate of #206. Working on integration of openssl 3.0 now...

**Comment by lukasf** [comment]
Openssl is now available in FFmpegInteropX 0.9.3!
